### ISSUE TITLE
Liberapay

### ISSUE THREAD

**Issue by mo8it** [julia4ta/tutorials#1]
Hello,

I love your content and I want to donate to you to support your work :)
I would love to donate to you over Liberapay. It would be awesome if you post the donation link on Github and YouTube.

Thanks!

**Comment by julia4ta** [comment]
Thank you for your interest! I am not currently on Liberapay. In fairness, I'm not really developing software yet. I'm primarily making tutorials on YouTube and sharing my code here. The best way to support the channel is by becoming a channel member. It's similar to Patreon, and channel members get advanced access to my new videos. If this is something you might be interested in, you can click on the "Join" button on my channel page: https://www.youtube.com/c/juliafortalentedamateurs Thanks!

**Comment by mo8it** [comment]
I actually wanted to support your content without a Google account. Liberapay is free open source.

**Comment by julia4ta** [comment]
Oh, I see. Well, the customer is always right! I have just created a Liberapay account. The username is the same as my GitHub account: julia4ta. Let me know if you have any issues with it. Thank you for your interest!

[julia4ta Liberapay](https://en.liberapay.com/julia4ta/)
