### ISSUE TITLE
Cry for tutorials on wrapping C++ libs/projects in julia

### ISSUE THREAD

**Issue by songtaogui** [julia4ta/tutorials#2]
Hi, 

Thanks for providing these wonderful julia tutorials.

Julia is a great language deserved to be used by more programmers. However, the julia ecosystem cannot compare with those of mature languages (like C++). Tutorials on wrapping C++ in julia could help a lot.

The official tutorials for [Cxx.jl](https://github.com/JuliaInterop/Cxx.jl), [CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl) and [Clang.jl](https://github.com/JuliaInterop/Clang.jl) are well documented, but not easy for readers (like me) that have little C++ programming experience.

Thus, I would appropriate if you can provide a tutorial for wrapping large C++ libs/projects in julia.

Best,

Songtao

**Comment by julia4ta** [comment]
I will be uploading a tutorial on how to call C++ code from Julia in about a month. However, it will be at a beginner level, so it may not be advanced enough for your needs. In the meanwhile, I would recommend checking out [CxxInterface.jl](https://github.com/eschnett/CxxInterface.jl) and [CxxCall.jl](https://github.com/jw3126/CxxCall.jl) . CxxInterface.jl is an alternative to Cxx.jl and CxxWrap.jl, while CxxCall.jl is syntactic sugar on top of CxxInterface.jl. Good luck!

**Comment by julia4ta** [comment]
I just uploaded a [tutorial](https://youtu.be/V5VbwtAb7xQ) providing a step-by-step workflow detailing how to use the CxxCall.jl package to embed C++ code in Julia, so I'm closing out this issue. Hope that helps! Here's a link to the [code](https://github.com/julia4ta/tutorials/tree/master/Series%2006/Tutorial%2006x09) for this tutorial.
